// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFnS1s7Xy24DpxUjdyDCs0AS1cNg7POqY',
    appId: '1:466415161876:web:d719bfa198ce91f663cd01',
    messagingSenderId: '466415161876',
    projectId: 'mentalwellnesstips-af69d',
    authDomain: 'mentalwellnesstips-af69d.firebaseapp.com',
    storageBucket: 'mentalwellnesstips-af69d.firebasestorage.app',
    measurementId: 'G-ELFGNN934H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGN3Xf1UkFAB1mioNxYVaBL6RPeh_-Rk8',
    appId: '1:466415161876:android:c3fef3a4dd4f81f863cd01',
    messagingSenderId: '466415161876',
    projectId: 'mentalwellnesstips-af69d',
    storageBucket: 'mentalwellnesstips-af69d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYcR_0NXnGfKl7mPWv5FpBW96fM62Or_Q',
    appId: '1:466415161876:ios:2ea270c645db0b1763cd01',
    messagingSenderId: '466415161876',
    projectId: 'mentalwellnesstips-af69d',
    storageBucket: 'mentalwellnesstips-af69d.firebasestorage.app',
    iosBundleId: 'com.example.mentalWellnessTips1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYcR_0NXnGfKl7mPWv5FpBW96fM62Or_Q',
    appId: '1:466415161876:ios:2ea270c645db0b1763cd01',
    messagingSenderId: '466415161876',
    projectId: 'mentalwellnesstips-af69d',
    storageBucket: 'mentalwellnesstips-af69d.firebasestorage.app',
    iosBundleId: 'com.example.mentalWellnessTips1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFnS1s7Xy24DpxUjdyDCs0AS1cNg7POqY',
    appId: '1:466415161876:web:fdfc0b6470b4cae663cd01',
    messagingSenderId: '466415161876',
    projectId: 'mentalwellnesstips-af69d',
    authDomain: 'mentalwellnesstips-af69d.firebaseapp.com',
    storageBucket: 'mentalwellnesstips-af69d.firebasestorage.app',
    measurementId: 'G-T0087MMF3R',
  );

}